name: grape
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  lottie: ^2.7.0
  flutter_ai_toolkit: ^0.10.0
  google_generative_ai: ^0.4.6
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.2.1
  provider: ^6.0.5
  geolocator: ^14.0.2
  geocoding: ^2.0.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  fonts:
    - family: ClimateCrisis
      fonts:
        - asset: assets/fonts/ClimateCrisis/ClimateCrisis.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter.ttf
        - asset: assets/fonts/Inter/Inter-italic.ttf
          style: italic
  
  assets:
    - assets/logo/
    - assets/animations/
    - assets/images/
    - assets/images/gifs/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  remove_alpha_ios: true
