name: grape
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  lottie: ^2.7.0
  flutter_ai_toolkit: ^0.10.0
  google_generative_ai: ^0.4.6
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^6.2.1
  provider: ^6.0.5
  geolocator: ^14.0.2
  geocoding: ^2.0.5
  shared_preferences: ^2.5.3
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  flutter_map_marker_cluster: ^8.2.2
  flutter_dotenv: ^6.0.0
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  fonts:
  
    - family: DM_Serif_Text
      fonts:
        - asset: assets/fonts/DM_Serif_Text/DMSerifText-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter.ttf
        - asset: assets/fonts/Inter/Inter-italic.ttf
          style: italic
  
  assets:
    - .env
    - assets/logo/
    - assets/animations/
    - assets/images/
    - assets/images/gifs/
    - assets/data/data.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  remove_alpha_ios: true

